Need to do some further cleaning on the data so will do so here

In [31]:
import pandas as pd
pd.options.mode.chained_assignment = None
#load in csv
df = pd.read_csv('uniqueevilmasterdoc.csv')
#start by removing . because they are rly hard to remove for some reason
dropped = df.drop([1206, 1364, 1365])
#remove @ and get 1593
cleaned_df = dropped[~dropped.spaces.str.contains("@")]
#remove - and get 1583
cleaned_df = cleaned_df[~cleaned_df.spaces.str.contains("-")]
#remove ! and get 1574
cleaned_df = cleaned_df[~cleaned_df.spaces.str.contains("!")]
#remove _ and get 1567
cleaned_df = cleaned_df[~cleaned_df.spaces.str.contains("_")]
#remove / and get 1567
cleaned_df = cleaned_df[~cleaned_df.spaces.str.contains("/")]
#remove & and get 1566
cleaned_df = cleaned_df[~cleaned_df.spaces.str.contains("&")]
#remove + and get 1558
cleaned_df = cleaned_df[~cleaned_df.spaces.str.contains('+', regex = False)]
#remove * and get 1487
cleaned_df = cleaned_df[~cleaned_df.spaces.str.contains("*", regex = False)]
#remove # and get 1486
cleaned_df = cleaned_df[~cleaned_df.spaces.str.contains("#")]
#remove ' and get 1479
cleaned_df = cleaned_df[~cleaned_df.spaces.str.contains("'")]
#remove . and get 1477
cleaned_df = cleaned_df[~cleaned_df.spaces.str.contains(".", regex = False)]

Now putting in the big offensive dataset

In [32]:
#load the big dataset
off = pd.read_csv('labeled_data.csv')
off.head()
#remove class of 2 
filt = off[off['class'] < 2]
#create hate speech and offensive language scores 
filt['hate_score'] = filt['hate_speech']/filt['count']
filt['off_score'] = filt['offensive_language']/filt['count']
filt.head()

,Unnamed: 0,count,hate_speech,offensive_language,neither,class,tweet,hate_score,off_score
1,1,3,0,3,0,1,!!!!! RT @mleew17: boy dats cold...tyga dwn ba...,0.000000,1.000000
2,2,3,0,3,0,1,!!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...,0.000000,1.000000
3,3,3,0,2,1,1,!!!!!!!!! RT @C_G_Anderson: @viva_based she lo...,0.000000,0.666667
4,4,6,0,6,0,1,!!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...,0.000000,1.000000
5,5,3,1,2,0,1,"!!!!!!!!!!!!!!!!!!""@T_Madison_x: The shit just...",0.333333,0.666667

Now counting the amount of times each item appears

In [45]:
off_words = list(cleaned_df['nospace'])
tweets = list(filt['tweet'])
cleaned_df['count_words'] = 1

#for item in off_words:
#    count = tweets.count(item_to_count)
for i, value in enumerate(off_words):
    count = sum(value in s for s in tweets)
    cleaned_df['count_words'][i] = count

#now get a csv with the cleaned data and count
cleaned_df.to_csv('cleaned_evilwords.csv', index=False)

In [44]:
cleaned_df.head()

    spaces  nospace  count_words
0     anal     anal           10
1     anus     anus            4
2  apeshit  apeshit            0
3      ass      ass         1923
4  asshole  asshole           44